# File:		makefile.g95  For wxIA - image acquisition
# Author:	Derry Bryson
# Created:	13-Feb-2003
# Updated:

#WXDIR = ../../..
WXDIR = $(WXWIN)

EXTRAINC=-I../../include

OBJECTS = \
	twainbase.o \
	twainmsw.o \
        ia.o \
        iatwainmsw.o

LIBTARGET = $(WXDIR)/lib/libia.a

include $(WXDIR)/src/makelib.g95