#
# File:         makefile.g95
# Author:       Julian Smart
# Created:      1999
# Updated:
# Copyright:    (c) Julian Smart, 1999
#
# Makefile for wxWindows sample (Cygwin/Mingw32).

#WXDIR = ../..
WXDIR = $(WXWIN)

EXTRAINC=-I../../include
EXTRALIBS=-lia

TARGET=iatest
OBJECTS = $(TARGET).o

include $(WXDIR)/src/makeprog.g95

